schoolSystem/SchoolSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('trainer/', include('trainer.urls')),
    path('courses/', include('courses.urls')), 
    path('events/', include('events.urls')),
    path("", include("core.urls")),
    path("api/", include("api.urls")),
    path("accounts/", include("registration.backends.default.urls")),



]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

schoolSystem/api/urls.py
from django.db import router
from django.urls import path, include
from rest_framework import routers, urlpatterns
from .views import EventViewSet, StudentViewSet
from .views import TrainerViewSet
from .views import CourseViewSet

router = routers.DefaultRouter()
router.register("students/", StudentViewSet)
router.register("trainers/", TrainerViewSet)
router.register("courses/", CourseViewSet)
router.register("events/", EventViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
]

schoolSystem/core/urls.py
from django.contrib.auth.decorators import login_required
from core.views import home
from django.conf.urls import include
from django.urls.conf import path



urlpatterns = [
path("", home, name="home_page"),
]

schoolSystem/events/urls.py
from django.conf.urls import url
from .import views
app_name = 'cal'

urlpatterns = [  
    url(r'^index/$', views.index, name='index'),
    url(r'^cal/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),  
]

schoolSystem/core/models.py
from django.db import models

# Create your models here.

schoolSystem/core/views.py
from datetime import date
from typing import Counter
from student.models import Student
from django.shortcuts import redirect, render
from student.models import Student
from trainer.models import Trainer
from courses.models import Courses

# Create your views here.

def home(request):
    if request.user.is_authenticated:
        student=Student.objects.count()
        trainer=Trainer.objects.count()
        courses=Courses.objects.count()
    
    

        data = {"student": student, "trainer": trainer, "course": courses}
        return render(request, "home_page.htm", data)
    else:
        return redirect("auth_login")

schoolSystem/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
    </header>
    <body>
       
        {%block content%}
        {% endblock %}
    </body>
</body>
</html>

https://github.com/akirachix/TechCare.git

schoolSystem/core/templates/home_page.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <title>
        {% block title %}School Management{% endblock %}
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600&display=swap" rel="stylesheet">
</head>

    <style>    
  
    body{
    background-image: url("https://pbs.twimg.com/media/EQEtxW4XsAAi_8t.jpg");
    margin-left: 300px;
    height:50%;
    width:80%;
    z-index:1;
    top: 0;
    overflow-x:hidden;
    background-size: 100%;
    font-family: 'Ubuntu', sans-serif;
    user-select: none;
    
    }
    html { overflow-y: scroll; }
    ul.navbar {
    list-style-type: none;
    position: fixed;
    top: 00px;
    left: 00px;
    width: 200px;
    height: 700px; 
}

    *{
        margin: 0;
        padding: 0;
        list-style: none;
        text-decoration: none;
      }
      
      .glasmo{
        margin-left: -110px;
        height:100%;
        width:75%;
        position: fixed;
        z-index:1;
        top: 110px;
        overflow-x:hidden;
        border-radius: 30px;
      
        }
      nav .logo{
        color: white;
        font-size: 33px;
        font-weight: bold;
        line-height: 70px;
        padding-left: 110px;
        text-decoration: none;
      }
      nav{
        position: fixed;
        width: 100%;
        height: 70px;
        background: purple;
        box-shadow: 0 3px 15px rgba(0,0,0,.4);
        right: 1px;
        z-index:2;
        text-decoration: none;
      }
      nav ul{
        float: right;
        margin-right: 30px;
        z-index:-2;
        text-decoration: none;
      }
      nav ul li{
        display: inline-block;
        z-index: 2;
        text-decoration: none;
      }
      nav ul li a{
        color: white;
        display: block;
        padding: 0 15px;
        line-height: 70px;
        font-size: 20px;
        background: purple;
        transition: .5s;
        z-index:2;
        text-decoration: none;
      }
      nav ul li a:hover,
      nav ul li a.active{
        color: #23dbdb;
        z-index:2;
        text-decoration: none;
      }
      nav ul ul{
        position: absolute;
        top: 85px;
        border-top: 3px solid #23dbdb;
        opacity: 0;
        visibility: hidden;
        z-index:2;
        text-decoration: none;
      }
      nav ul li:hover > ul{
        top: 70px;
        opacity: 1;
        visibility: visible;
        transition: .3s linear;
        z-index: 2;
        text-decoration: none;
      }
      nav ul ul li{
        width: 150px;
        display: list-item;
        position: relative;
        border: 1px solid #042331;
        border-top: none;
        z-index:2;
        text-decoration: none;
      }
      nav ul ul li a{
        line-height: 50px;
        z-index:-2;
        text-decoration: none;
      }
      nav ul ul ul{
        border-top: none;
        z-index:-2;
        text-decoration: none;
      }
      nav ul ul ul li{
        position: relative;
        top: -70px;
        left: 150px;
        z-index:-2;
        text-decoration: none;
      }
      nav ul ul li a i{
        margin-left: 45px;
        z-index:-2;
        text-decoration: none;

      }
      section{
        background: url(bg.jpeg);
        background-position: center;
        background-size: cover;
        height: 100vh;
      }
       #black{
           color: #23dbdb;
       }
    
    </style>

<body> 
    <nav>
    
        <label class="logo"><span>Akira</span><span id="black">Chix.</span></label>
        <ul>
           <li><a style="text-decoration: none;" class="active" href="#">Home</a></li>
           <li>
              <a style="text-decoration: none;" href="#">Calendar
              <i class="fas fa-caret-down"></i>
              </a>
              <ul>
                 <li><a style="text-decoration: none;" href="{%url 'cal:calendar'%}">Create event</a></li>
                 <li><a style="text-decoration: none;" href="{%url 'cal:calendar'%}">Events</a></li>
              </ul>

              <li>
                 <a style="text-decoration: none;" href="#">Course
                 <i class="fas fa-caret-down"></i>
                 </a>
                 <ul>
                    <li><a style="text-decoration: none;"  href="{% url 'register_courses'%}">Add Course</a></li>
                    <li><a style="text-decoration: none;"  href="{% url 'course_list'%}">Course List</a></li>
                 </ul>

                 <li>
                   <a style="text-decoration: none;"  href="#">Students
                   <i class="fas fa-caret-down"></i>
                   </a>
                   <ul>
                      <li><a style="text-decoration: none;"  href="{% url 'register_student'%}">Register</a></li>
                      <li><a style="text-decoration: none;"  href="{% url 'student_list'%}">student list</a></li>
                   </ul>

                   <li>
                       <a style="text-decoration: none;"  href="#">Trainers
                       <i class="fas fa-caret-down"></i>
                       </a>
                       <ul>
                          <li><a style="text-decoration: none;"  href="{% url 'register_trainer'%}">New Trainer</a></li>
                          <li><a style="text-decoration: none;"  href="{% url 'trainer_list'%}">Trainer list</a></li>
                       </ul>
         
     </ul>
     </nav>
    
    
	{% block content %}

    <img class="glasmo" src="https://pbs.twimg.com/media/EQEtxW4XsAAi_8t.jpg">
  
	{% endblock %}  
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<a href="accounts/login">Login</a>
<a href="accounts/register">Register</a>
</body>
</html>