schoolSystem/SchoolSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('trainer/', include('trainer.urls')),
    path('courses/', include('courses.urls')), 
    path('events/', include('events.urls')),
    path("", include("core.urls")),
    path("api/", include("api.urls")),
    path("accounts/", include("registration.backends.default.urls")),



]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

schoolSystem/api/urls.py
from django.db import router
from django.urls import path, include
from rest_framework import routers, urlpatterns
from .views import EventViewSet, StudentViewSet
from .views import TrainerViewSet
from .views import CourseViewSet

router = routers.DefaultRouter()
router.register("students/", StudentViewSet)
router.register("trainers/", TrainerViewSet)
router.register("courses/", CourseViewSet)
router.register("events/", EventViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
]

schoolSystem/events/urls.py
from django.conf.urls import url
from .import views
app_name = 'cal'

urlpatterns = [  
    url(r'^index/$', views.index, name='index'),
    url(r'^cal/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),  
]

schoolSystem/events/models.py
from django.conf.urls import url
from django.db import models
import datetime
from django.urls import reverse

# Create your models here.
class Events(models.Model):
    event_name=models.CharField(max_length=12)
    event_location=models.CharField(max_length=10)
    start_time = models.DateTimeField(default=datetime.date.today)
    end_time = models.DateTimeField(default=datetime.date.today)

def __str__(self):
    return self.event_name

@property
def get_htm_url(self):
    url = reverse('event_edit', args=(self.id,))
    return f'<p>{self.event_name}</p><a href="{url}">edit</a>'

schoolSystem/events/forms.py
from django import forms
from django.forms.widgets import DateInput, TextInput
from.models import Events
from django.forms import fields

class EventRegistrationForm(forms.ModelForm):
    class Meta:
        model =Events
        fields="__all__"
        widgets = {
      'start_time': DateInput(attrs=
      {
        'type': 'datetime-local',
        'style': 'max-width: 300px;',
        'class': "form-control",
      }, 

      format='%Y-%m-%dT%H:%M'),

      'end_time': DateInput(attrs=
      {
        'type': 'datetime-local',
        'style': 'max-width: 300px;',
        'class': "form-control",    
      },
       
      format='%Y-%m-%dT%H:%M'),

      'event_name':TextInput(attrs=
      {
        'class': "form-control",
        'style': 'max-width: 300px;',
        'placeholder': 'Name'
      }),

      'event_location':TextInput(attrs=
      {
        'class': "form-control",
        'style': 'max-width: 300px;',
        'placeholder': 'Event Venue'
      }),     
    }

    def __init__(self, *args, **kwargs):
        super(EventRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

schoolSystem/events/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventRegistrationForm
# Create your views here.


def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Events
    template_name = 'cal/calendar.htm'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Events()
    if event_id:
        instance = get_object_or_404(Events, pk=event_id)
    else:
        instance = Events()

    form = EventRegistrationForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/events.htm', {'form': form})




# def register_event(request):
#     if request.method=="POST":
#         form=EventRegistrationForm(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('register_event')
#         else:
#             print(form.errors)
#     else:
#         form=EventRegistrationForm()
#     return render(request,"register_event.htm", {"form":form})

# def event_list(request):
#     events = Events.objects.all()
#     return render(request, "event_list.htm", {"events":events})

schoolSystem/events/templates/cal/base.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/style.css' %}">

<title>Calender</title>
</head>

<body>
  <nav>
    
    <label class="logo"><span>Akira</span><span id="black">Chix.</span></label>
    <ul>
       <li><a class="active" href="#">Home</a></li>
       <li>
          <a href="#">Calendar
          <i class="fas fa-caret-down"></i>
          </a>
          <ul>
             <li><a href="{%url 'cal:calendar'%}">Create event</a></li>
             <li><a href="{%url 'cal:calendar'%}">Events</a></li>
          </ul>

          <li>
             <a href="#">Course
             <i class="fas fa-caret-down"></i>
             </a>
             <ul>
                <li><a href="{% url 'register_courses'%}">Add Course</a></li>
                <li><a href="{% url 'course_list'%}">Course List</a></li>
             </ul>

             <li>
               <a href="#">Students
               <i class="fas fa-caret-down"></i>
               </a>
               <ul>
                  <li><a href="{% url 'register_student'%}">Register</a></li>
                  <li><a href="{% url 'student_list'%}">student list</a></li>
               </ul>

               <li>
                   <a href="#">Trainers
                   <i class="fas fa-caret-down"></i>
                   </a>
                   <ul>
                      <li><a href="{% url 'register_trainer'%}">New Trainer</a></li>
                      <li><a href="{% url 'trainer_list'%}">Trainer list</a></li>
                   </ul>
     
 </ul>
 </nav>
 <h1>CodeHive Calendar</h1>
  <img src="https://miro.medium.com/max/1838/1*dIXJZdx-BAkU13P0qoUjuw.jpeg" alt="">
  <style>
    
    html { overflow-y: scroll; }
    *{
        margin: 0;
        padding: 0;
        list-style: none;
        text-decoration: none;
      }
      
body {
overflow: hidden;
z-index: 2;


}
nav{
  position: fixed;
  width: 100%;
  height: 70px;
  background: purple;
  box-shadow: 0 3px 15px rgba(0,0,0,.4);
  right: 1px;
  z-index:2;
}
nav ul{
  float: right;
  margin-right: 30px;
  z-index:-2;
}
nav ul li{
  display: inline-block;
  z-index: 2;
}
nav ul li a{
  color: white;
  display: block;
  padding: 0 15px;
  line-height: 70px;
  font-size: 20px;
  background: purple;
  transition: .5s;
  z-index:2;
}
nav ul li a:hover,
nav ul li a.active{
  color: #23dbdb;
  z-index:2;
}
nav ul ul{
  position: absolute;
  top: 85px;
  border-top: 3px solid #23dbdb;
  opacity: 0;
  visibility: hidden;
  z-index:2;
}
nav ul li:hover > ul{
  top: 70px;
  opacity: 1;
  visibility: visible;
  transition: .3s linear;
  z-index: 2;
}
nav ul ul li{
  width: 150px;
  display: list-item;
  position: relative;
  border: 1px solid #042331;
  border-top: none;
  z-index:2;
}
nav ul ul li a{
  line-height: 50px;
  z-index:-2;
}
nav ul ul ul{
  border-top: none;
  z-index:-2;
}
nav ul ul ul li{
  position: relative;
  top: -70px;
  left: 150px;
  z-index:-2;
}
nav ul ul li a i{
  margin-left: 45px;
  z-index:-2;

}
section{
  background: url(bg.jpeg);
  background-position: center;
  background-size: cover;
  height: 100vh;
}
 #black{
     color: #23dbdb;
 }
 nav .logo{
  color: white;
  font-size: 33px;
  font-weight: bold;
  line-height: 70px;
  padding-left: 110px;
}
.img{
  width:100%;
  z-index: 1;
  overflow: hidden;
  

}

.info {
  border-color:purple;
  color: purple;
}

.info:hover {
  background:purple;
  color: white;
}

.info {
  border-color: purple;
  color:purple;
  margin-right:310px;
  margin-left:-30px;
}

.info:hover {
  background:purple;
  color: white;
}

.container {
  margin-top: 10px;
  background-color: white;
  margin-left: 30%;
  width: 500px;
  border:3px solid purple;
  box-shadow: 8px 8px 8px 9px purple;
  border-radius: 10px;
}

button{

  background-color: purple;
  color: white;
  border-radius: 10px;
  padding: 10px;
  width: 300px;
  display: flex;
  justify-content: center;
  align-items: center;

  
  
}

h1{
  padding-top: 10px;
  color:purple;
  font-weight: bold;
  justify-content: center;
  align-items: center;
  display: flex;
}

p{
  color: rgb(51, 4, 4);
}

form{
  padding-top: 20px;
  padding-left: 80px;
  padding-bottom: 20px;
}

.form-group{
  border-color: purple;;
}

hr{
  background-color:purple;;
  height: 3px;
  margin-left: -30%;
  margin-top: 0.3%;
}

.left {
  float: left;
}

.right {
  float: right;
}

.clearfix {
  margin: 15px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-left: 300px;
}

/* App styles */
.title {
  text-align: center;
  margin: 10px;
  margin-left: -30%;
}

.calendar {
  width: 58%;
  margin-left: 20%;
  font-size: 13px;
  background:rgb(27, 21, 24);
  color: white;
}

.calendar tr, .calendar td{
  border: 1px solid purple;;
}

.calendar td:hover{
  border: 2px solid rgb(201, 175, 187);
  cursor: pointer;
}

.calendar th {
  padding: 10px;
  text-align: center;
  font-size: 18px;
}

.calendar td{
  width: 100px;
  height: 50px;
  padding: 20px 0px 0px 5px;
}

.month {
  font-size: 25px;
}

.date {
  font-size: 16px;
}

ul {
  height: 100%;
  padding: 0px 5px 0px 20px;
}

a {
  color:purple;
}

textarea{
  width: 100%;
}
  </style>


  <hr>

  {% block content %}
  {% endblock %}

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

schoolSystem/events/templates/cal/calendar.htm
{% extends 'cal/event_list.htm' %}



{% block content %}
<div class="clearfix">
	<a class="btn info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn info" href="{% url 'cal:event_new' %}"> Add Event </a>
</div>
{{ calendar }}
{% endblock %}

schoolSystem/events/templates/cal/event_list.htm
{% extends 'cal/base.htm' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn info" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<body>
<style>
    </style>
<div class="container">
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="register"> Submit </button>
</form>
</div>
</body>
</html>
{% endblock %}

schoolSystem/events/templates/cal/events.htm
<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js">
        </script>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  
    <!-- <link rel="stylesheet" href="style.css"> -->
    <title>Calendar</title>
</head>
<body>
    <nav>
    
        <label class="logo"><span>Akira</span><span id="black">Chix.</span></label>
        <ul>
           <li><a class="active" href="#">Home</a></li>
           <li>
              <a href="#">Calendar
              <i class="fas fa-caret-down"></i>
              </a>
              <ul>
                 <li><a href="{%url 'cal:calendar'%}">Create event</a></li>
                 <li><a href="{%url 'cal:calendar'%}">Events</a></li>
              </ul>

              <li>
                 <a href="#">Course
                 <i class="fas fa-caret-down"></i>
                 </a>
                 <ul>
                    <li><a href="{% url 'register_courses'%}">Add Course</a></li>
                    <li><a href="{% url 'course_list'%}">Course List</a></li>
                 </ul>

                 <li>
                   <a href="#">Students
                   <i class="fas fa-caret-down"></i>
                   </a>
                   <ul>
                      <li><a href="{% url 'register_student'%}">Register</a></li>
                      <li><a href="{% url 'student_list'%}">student list</a></li>
                   </ul>

                   <li>
                       <a href="#">Trainers
                       <i class="fas fa-caret-down"></i>
                       </a>
                       <ul>
                          <li><a href="{% url 'register_trainer'%}">New Trainer</a></li>
                          <li><a href="{% url 'trainer_list'%}">Trainer list</a></li>
                       </ul>
         
     </ul>
     </nav>
    <style>
        .type{
            font-size: 27px;
        }
h3{
          text-align: center;
          display: flex;
          justify-content: center;
          color: rgb(16, 16, 114);
          font-family: 'Montserrat', sans-serif;

      }
        body{
            background-color: rgb(123, 123, 173);
            align-items: center;
            justify-content: center;
            font-size: 20px;
            font-family: 'Montserrat', sans-serif;
            color:navy;
            background: linear-gradient(
      to right,
      rgba(21, 81, 170, 0.9),
      rgba(221, 14, 159, 0.9)
    );
        }
     
       select{
           width: 100%;
           padding: 8px 8px;
           border-radius: 3px;
           transition: all 0.3;
           margin: 20px auto;
           background: transparent;
           box-shadow: 0 0 5px white inset;
       } 
       .wrapper{ 
      max-width: 500px;
      /* width: 80%; */
      background: #fff;
      margin: 20px auto;
      padding: 30px;
      box-shadow: 1px 1px 40px black;
      border-radius: 10px;
      background: linear-gradient(to right bottom, rgba(255,255,255,0.7),
                                                   rgba(255,255,255,0.3));
                                                 
       }
      
       
       input{
           width: 100%;
           outline: none;
           border: 1px solid ;
           font-size: 15px;
           padding: 8px 8px;
           border-radius: 5px;
           background-color: transparent;
           box-shadow: 0 0 5px white inset;
       }
   
      button{
          background-color: navy;
          align-items: 50%;
          margin-left: 35%;
          top: 30px;
          height: 50px;
          width: 90px;
          font-size: large;
          border-radius: 5px;
          padding: 10px;
          transition: width 1s, height 4s;
          color: white;
      }
      button:hover{
          background-color: black;
          color: white;
          width: 100px;
          height: 60px;
          font-size: 20px;
          
      }
      
      .pic{
          background-size: contain;
          border-radius: 50%;
          text-align: center;
          height: 150px;
          margin-left: 120px;
          margin-bottom: 20px;
        
      }
     
     
    </style>


    <div class="wrapper">
        <div class="form">
    <form method="POST">
        {%csrf_token%}
        <img src="https://hakeema.imgix.net/matterfund/unit/5e2ccac81eafe8001cb1d2c8-3e1444.png?w=250&h=250&fit=fillmax&bg=FFFFFFFF&pad=5&auto=format" class="pic">

        <div class="type"></div>
        <h3>CodeHive Calendar</h3>
        
        {{form.as_p}}
        <button class="button">Submit</button>
        </div>
        </div>
      
    </form>
    <script>
    var typed = new Typed(".type", {
        strings: ["WELCOME TO AKIRACHIX, CODEHIVE 2021!"],
        typeSpeed: 110,
        // loop: true
    });
    </script>
</body>
</html>

schoolSystem/events/templates/cal/register_event.htm
<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js">
        </script>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  
    <!-- <link rel="stylesheet" href="style.css"> -->
    <title>Calendar</title>
</head>
<body>
    <nav>
    
        <label class="logo"><span>Akira</span><span id="black">Chix.</span></label>
        <ul>
           <li><a class="active" href="#">Home</a></li>
           <li>
              <a href="#">Calendar
              <i class="fas fa-caret-down"></i>
              </a>
              <ul>
                 <li><a href="{%url 'cal:calendar'%}">Create event</a></li>
                 <li><a href="{%url 'cal:calendar'%}">Events</a></li>
              </ul>

              <li>
                 <a href="#">Course
                 <i class="fas fa-caret-down"></i>
                 </a>
                 <ul>
                    <li><a href="{% url 'register_courses'%}">Add Course</a></li>
                    <li><a href="{% url 'course_list'%}">Course List</a></li>
                 </ul>

                 <li>
                   <a href="#">Students
                   <i class="fas fa-caret-down"></i>
                   </a>
                   <ul>
                      <li><a href="{% url 'register_student'%}">Register</a></li>
                      <li><a href="{% url 'student_list'%}">student list</a></li>
                   </ul>

                   <li>
                       <a href="#">Trainers
                       <i class="fas fa-caret-down"></i>
                       </a>
                       <ul>
                          <li><a href="{% url 'register_trainer'%}">New Trainer</a></li>
                          <li><a href="{% url 'trainer_list'%}">Trainer list</a></li>
                       </ul>
         
     </ul>
     </nav>
    <style>
        nav .logo{
            color: white;
            font-size: 33px;
            font-weight: bold;
            line-height: 70px;
            padding-left: 110px;
          }
        nav{
            position: fixed;
            width: 100%;
            height: 70px;
            background: purple;
            box-shadow: 0 3px 15px rgba(0,0,0,.4);
            right: 1px;
            z-index:2;
          }
          nav ul{
            float: right;
            margin-right: 30px;
            z-index:-2;
          }
          nav ul li{
            display: inline-block;
            z-index: 2;
          }
          nav ul li a{
            color: white;
            display: block;
            padding: 0 15px;
            line-height: 70px;
            font-size: 20px;
            background: purple;
            transition: .5s;
            z-index:2;
          }
          nav ul li a:hover,
          nav ul li a.active{
            color: #23dbdb;
            z-index:2;
          }
          nav ul ul{
            position: absolute;
            top: 85px;
            border-top: 3px solid #23dbdb;
            opacity: 0;
            visibility: hidden;
            z-index:2;
          }
          nav ul li:hover > ul{
            top: 70px;
            opacity: 1;
            visibility: visible;
            transition: .3s linear;
            z-index: 2;
          }
          nav ul ul li{
            width: 150px;
            display: list-item;
            position: relative;
            border: 1px solid #042331;
            border-top: none;
            z-index:2;
          }
          nav ul ul li a{
            line-height: 50px;
            z-index:-2;
          }
          nav ul ul ul{
            border-top: none;
            z-index:-2;
          }
          nav ul ul ul li{
            position: relative;
            top: -70px;
            left: 150px;
            z-index:-2;
          }
          nav ul ul li a i{
            margin-left: 45px;
            z-index:-2;
    
          }
          section{
            background: url(bg.jpeg);
            background-position: center;
            background-size: cover;
            height: 100vh;
          }
           #black{
               color: #23dbdb;
           }
        .type{
            font-size: 27px;
        }
h3{
          text-align: center;
          display: flex;
          justify-content: center;
          color: rgb(16, 16, 114);
          font-family: 'Montserrat', sans-serif;

      }
        body{
            background-color: rgb(123, 123, 173);
            align-items: center;
            justify-content: center;
            font-size: 20px;
            font-family: 'Montserrat', sans-serif;
            color:navy;
            background: linear-gradient(
      to right,
      rgba(21, 81, 170, 0.9),
      rgba(221, 14, 159, 0.9)
    );
        }
     
       select{
           width: 100%;
           padding: 8px 8px;
           border-radius: 3px;
           transition: all 0.3;
           margin: 20px auto;
           background: transparent;
           box-shadow: 0 0 5px white inset;
       } 
       .wrapper{ 
      max-width: 500px;
      /* width: 80%; */
      background: #fff;
      margin: 20px auto;
      padding: 30px;
      box-shadow: 1px 1px 40px black;
      border-radius: 10px;
      background: linear-gradient(to right bottom, rgba(255,255,255,0.7),
                                                   rgba(255,255,255,0.3));
                                                 
       }
      
       
       input{
           width: 100%;
           outline: none;
           border: 1px solid ;
           font-size: 15px;
           padding: 8px 8px;
           border-radius: 5px;
           background-color: transparent;
           box-shadow: 0 0 5px white inset;
       }
   
      button{
          background-color: navy;
          align-items: 50%;
          margin-left: 35%;
          top: 30px;
          height: 50px;
          width: 90px;
          font-size: large;
          border-radius: 5px;
          padding: 10px;
          transition: width 1s, height 4s;
          color: white;
      }
      button:hover{
          background-color: black;
          color: white;
          width: 100px;
          height: 60px;
          font-size: 20px;
          
      }
      
      .pic{
          background-size: contain;
          border-radius: 50%;
          text-align: center;
          height: 150px;
          margin-left: 120px;
          margin-bottom: 20px;
        
      }
     
     
    </style>


    <div class="wrapper">
        <div class="form">
    <form method="POST">
        {%csrf_token%}
        <img src="https://hakeema.imgix.net/matterfund/unit/5e2ccac81eafe8001cb1d2c8-3e1444.png?w=250&h=250&fit=fillmax&bg=FFFFFFFF&pad=5&auto=format" class="pic">

        <div class="type"></div>
        <h3>CodeHive Calendar</h3>
        
        {{form.as_p}}
        <button class="button">Submit</button>
        </div>
        </div>
      
    </form>
    <script>
    var typed = new Typed(".type", {
        strings: ["WELCOME TO AKIRACHIX, CODEHIVE 2021!"],
        typeSpeed: 110,
        // loop: true
    });
    </script>
</body>
</html>